FROM python:3.11-slim

WORKDIR /app

RUN pip install fastapi uvicorn psycopg2-binary reportlab qrcode Pillow

COPY certificate_pdf.py .

CMD ["uvicorn", "certificate_pdf:app", "--host", "0.0.0.0", "--port", "8003"]
